[base]
swarm_type = 'covid'
n_agents = 100
object_location  = [450, 425]

[screen]
frames = inf
height = 1000
width  = 1000

[population]
convex    = true
obstacles = false
outside   = false

[person]
#velocity force
max_force         = 8.0
#view of neighbor agents
radius_view       = 50  # This

[agent]
height    = 5.0
width     = 5
dt        = 0.2
mass      = 20
max_speed = 7.0
min_speed = 4.0